(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let create_networking_v1_ingress_class ~sw client ~body ?pretty ?dry_run ?field_manager ?field_validation () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/ingressclasses" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldManager" (fun x -> x) field_manager in
    let uri = Request.maybe_add_query_param uri "fieldValidation" (fun x -> x) field_validation in
    let body = Request.write_as_json_body Io_k8s_api_networking_v1_ingress_class.to_yojson body in
    let resp, body = Cohttp_eio.Client.call ~sw client `POST uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress_class.of_yojson) resp body

let create_networking_v1_namespaced_ingress ~sw client ~namespace ~body ?pretty ?dry_run ?field_manager ?field_validation () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/ingresses" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldManager" (fun x -> x) field_manager in
    let uri = Request.maybe_add_query_param uri "fieldValidation" (fun x -> x) field_validation in
    let body = Request.write_as_json_body Io_k8s_api_networking_v1_ingress.to_yojson body in
    let resp, body = Cohttp_eio.Client.call ~sw client `POST uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress.of_yojson) resp body

let create_networking_v1_namespaced_network_policy ~sw client ~namespace ~body ?pretty ?dry_run ?field_manager ?field_validation () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/networkpolicies" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldManager" (fun x -> x) field_manager in
    let uri = Request.maybe_add_query_param uri "fieldValidation" (fun x -> x) field_validation in
    let body = Request.write_as_json_body Io_k8s_api_networking_v1_network_policy.to_yojson body in
    let resp, body = Cohttp_eio.Client.call ~sw client `POST uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_network_policy.of_yojson) resp body

let delete_networking_v1_collection_ingress_class ~sw client ?pretty ?continue ?dry_run ?field_selector ?grace_period_seconds ?label_selector ?limit ?orphan_dependents ?propagation_policy ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ~body () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/ingressclasses" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "gracePeriodSeconds" Int32.to_string grace_period_seconds in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "orphanDependents" string_of_bool orphan_dependents in
    let uri = Request.maybe_add_query_param uri "propagationPolicy" (fun x -> x) propagation_policy in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let body = Request.write_as_json_body Io_k8s_apimachinery_pkg_apis_meta_v1_delete_options.to_yojson body in
    let resp, body = Cohttp_eio.Client.call ~sw client `DELETE uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_status.of_yojson) resp body

let delete_networking_v1_collection_namespaced_ingress ~sw client ~namespace ?pretty ?continue ?dry_run ?field_selector ?grace_period_seconds ?label_selector ?limit ?orphan_dependents ?propagation_policy ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ~body () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/ingresses" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "gracePeriodSeconds" Int32.to_string grace_period_seconds in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "orphanDependents" string_of_bool orphan_dependents in
    let uri = Request.maybe_add_query_param uri "propagationPolicy" (fun x -> x) propagation_policy in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let body = Request.write_as_json_body Io_k8s_apimachinery_pkg_apis_meta_v1_delete_options.to_yojson body in
    let resp, body = Cohttp_eio.Client.call ~sw client `DELETE uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_status.of_yojson) resp body

let delete_networking_v1_collection_namespaced_network_policy ~sw client ~namespace ?pretty ?continue ?dry_run ?field_selector ?grace_period_seconds ?label_selector ?limit ?orphan_dependents ?propagation_policy ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ~body () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/networkpolicies" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "gracePeriodSeconds" Int32.to_string grace_period_seconds in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "orphanDependents" string_of_bool orphan_dependents in
    let uri = Request.maybe_add_query_param uri "propagationPolicy" (fun x -> x) propagation_policy in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let body = Request.write_as_json_body Io_k8s_apimachinery_pkg_apis_meta_v1_delete_options.to_yojson body in
    let resp, body = Cohttp_eio.Client.call ~sw client `DELETE uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_status.of_yojson) resp body

let delete_networking_v1_ingress_class ~sw client ~name ?pretty ?dry_run ?grace_period_seconds ?orphan_dependents ?propagation_policy ~body () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/ingressclasses/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "gracePeriodSeconds" Int32.to_string grace_period_seconds in
    let uri = Request.maybe_add_query_param uri "orphanDependents" string_of_bool orphan_dependents in
    let uri = Request.maybe_add_query_param uri "propagationPolicy" (fun x -> x) propagation_policy in
    let body = Request.write_as_json_body Io_k8s_apimachinery_pkg_apis_meta_v1_delete_options.to_yojson body in
    let resp, body = Cohttp_eio.Client.call ~sw client `DELETE uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_status.of_yojson) resp body

let delete_networking_v1_namespaced_ingress ~sw client ~name ~namespace ?pretty ?dry_run ?grace_period_seconds ?orphan_dependents ?propagation_policy ~body () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/ingresses/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "gracePeriodSeconds" Int32.to_string grace_period_seconds in
    let uri = Request.maybe_add_query_param uri "orphanDependents" string_of_bool orphan_dependents in
    let uri = Request.maybe_add_query_param uri "propagationPolicy" (fun x -> x) propagation_policy in
    let body = Request.write_as_json_body Io_k8s_apimachinery_pkg_apis_meta_v1_delete_options.to_yojson body in
    let resp, body = Cohttp_eio.Client.call ~sw client `DELETE uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_status.of_yojson) resp body

let delete_networking_v1_namespaced_network_policy ~sw client ~name ~namespace ?pretty ?dry_run ?grace_period_seconds ?orphan_dependents ?propagation_policy ~body () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/networkpolicies/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "gracePeriodSeconds" Int32.to_string grace_period_seconds in
    let uri = Request.maybe_add_query_param uri "orphanDependents" string_of_bool orphan_dependents in
    let uri = Request.maybe_add_query_param uri "propagationPolicy" (fun x -> x) propagation_policy in
    let body = Request.write_as_json_body Io_k8s_apimachinery_pkg_apis_meta_v1_delete_options.to_yojson body in
    let resp, body = Cohttp_eio.Client.call ~sw client `DELETE uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_status.of_yojson) resp body

let get_networking_v1_api_resources ~sw client () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_api_resource_list.of_yojson) resp body

let list_networking_v1_ingress_class ~sw client ?pretty ?allow_watch_bookmarks ?continue ?field_selector ?label_selector ?limit ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ?watch () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/ingressclasses" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "allowWatchBookmarks" string_of_bool allow_watch_bookmarks in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let uri = Request.maybe_add_query_param uri "watch" string_of_bool watch in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress_class_list.of_yojson) resp body

let list_networking_v1_ingress_for_all_namespaces ~sw client ?allow_watch_bookmarks ?continue ?field_selector ?label_selector ?limit ?pretty ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ?watch () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/ingresses" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.maybe_add_query_param uri "allowWatchBookmarks" string_of_bool allow_watch_bookmarks in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let uri = Request.maybe_add_query_param uri "watch" string_of_bool watch in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress_list.of_yojson) resp body

let list_networking_v1_namespaced_ingress ~sw client ~namespace ?pretty ?allow_watch_bookmarks ?continue ?field_selector ?label_selector ?limit ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ?watch () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/ingresses" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "allowWatchBookmarks" string_of_bool allow_watch_bookmarks in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let uri = Request.maybe_add_query_param uri "watch" string_of_bool watch in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress_list.of_yojson) resp body

let list_networking_v1_namespaced_network_policy ~sw client ~namespace ?pretty ?allow_watch_bookmarks ?continue ?field_selector ?label_selector ?limit ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ?watch () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/networkpolicies" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "allowWatchBookmarks" string_of_bool allow_watch_bookmarks in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let uri = Request.maybe_add_query_param uri "watch" string_of_bool watch in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_network_policy_list.of_yojson) resp body

let list_networking_v1_network_policy_for_all_namespaces ~sw client ?allow_watch_bookmarks ?continue ?field_selector ?label_selector ?limit ?pretty ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ?watch () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/networkpolicies" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.maybe_add_query_param uri "allowWatchBookmarks" string_of_bool allow_watch_bookmarks in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let uri = Request.maybe_add_query_param uri "watch" string_of_bool watch in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_network_policy_list.of_yojson) resp body

let patch_networking_v1_ingress_class ~sw client ~name ~body ?pretty ?dry_run ?field_manager ?field_validation ?force () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/ingressclasses/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldManager" (fun x -> x) field_manager in
    let uri = Request.maybe_add_query_param uri "fieldValidation" (fun x -> x) field_validation in
    let uri = Request.maybe_add_query_param uri "force" string_of_bool force in
    let body = Request.write_json_body  body in
    let resp, body = Cohttp_eio.Client.call ~sw client `PATCH uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress_class.of_yojson) resp body

let patch_networking_v1_namespaced_ingress ~sw client ~name ~namespace ~body ?pretty ?dry_run ?field_manager ?field_validation ?force () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/ingresses/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldManager" (fun x -> x) field_manager in
    let uri = Request.maybe_add_query_param uri "fieldValidation" (fun x -> x) field_validation in
    let uri = Request.maybe_add_query_param uri "force" string_of_bool force in
    let body = Request.write_json_body  body in
    let resp, body = Cohttp_eio.Client.call ~sw client `PATCH uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress.of_yojson) resp body

let patch_networking_v1_namespaced_ingress_status ~sw client ~name ~namespace ~body ?pretty ?dry_run ?field_manager ?field_validation ?force () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/ingresses/{name}/status" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldManager" (fun x -> x) field_manager in
    let uri = Request.maybe_add_query_param uri "fieldValidation" (fun x -> x) field_validation in
    let uri = Request.maybe_add_query_param uri "force" string_of_bool force in
    let body = Request.write_json_body  body in
    let resp, body = Cohttp_eio.Client.call ~sw client `PATCH uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress.of_yojson) resp body

let patch_networking_v1_namespaced_network_policy ~sw client ~name ~namespace ~body ?pretty ?dry_run ?field_manager ?field_validation ?force () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/networkpolicies/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldManager" (fun x -> x) field_manager in
    let uri = Request.maybe_add_query_param uri "fieldValidation" (fun x -> x) field_validation in
    let uri = Request.maybe_add_query_param uri "force" string_of_bool force in
    let body = Request.write_json_body  body in
    let resp, body = Cohttp_eio.Client.call ~sw client `PATCH uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_network_policy.of_yojson) resp body

let read_networking_v1_ingress_class ~sw client ~name ?pretty () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/ingressclasses/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress_class.of_yojson) resp body

let read_networking_v1_namespaced_ingress ~sw client ~name ~namespace ?pretty () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/ingresses/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress.of_yojson) resp body

let read_networking_v1_namespaced_ingress_status ~sw client ~name ~namespace ?pretty () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/ingresses/{name}/status" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress.of_yojson) resp body

let read_networking_v1_namespaced_network_policy ~sw client ~name ~namespace ?pretty () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/networkpolicies/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_network_policy.of_yojson) resp body

let replace_networking_v1_ingress_class ~sw client ~name ~body ?pretty ?dry_run ?field_manager ?field_validation () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/ingressclasses/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldManager" (fun x -> x) field_manager in
    let uri = Request.maybe_add_query_param uri "fieldValidation" (fun x -> x) field_validation in
    let body = Request.write_as_json_body Io_k8s_api_networking_v1_ingress_class.to_yojson body in
    let resp, body = Cohttp_eio.Client.call ~sw client `PUT uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress_class.of_yojson) resp body

let replace_networking_v1_namespaced_ingress ~sw client ~name ~namespace ~body ?pretty ?dry_run ?field_manager ?field_validation () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/ingresses/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldManager" (fun x -> x) field_manager in
    let uri = Request.maybe_add_query_param uri "fieldValidation" (fun x -> x) field_validation in
    let body = Request.write_as_json_body Io_k8s_api_networking_v1_ingress.to_yojson body in
    let resp, body = Cohttp_eio.Client.call ~sw client `PUT uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress.of_yojson) resp body

let replace_networking_v1_namespaced_ingress_status ~sw client ~name ~namespace ~body ?pretty ?dry_run ?field_manager ?field_validation () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/ingresses/{name}/status" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldManager" (fun x -> x) field_manager in
    let uri = Request.maybe_add_query_param uri "fieldValidation" (fun x -> x) field_validation in
    let body = Request.write_as_json_body Io_k8s_api_networking_v1_ingress.to_yojson body in
    let resp, body = Cohttp_eio.Client.call ~sw client `PUT uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_ingress.of_yojson) resp body

let replace_networking_v1_namespaced_network_policy ~sw client ~name ~namespace ~body ?pretty ?dry_run ?field_manager ?field_validation () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/namespaces/{namespace}/networkpolicies/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "dryRun" (fun x -> x) dry_run in
    let uri = Request.maybe_add_query_param uri "fieldManager" (fun x -> x) field_manager in
    let uri = Request.maybe_add_query_param uri "fieldValidation" (fun x -> x) field_validation in
    let body = Request.write_as_json_body Io_k8s_api_networking_v1_network_policy.to_yojson body in
    let resp, body = Cohttp_eio.Client.call ~sw client `PUT uri ~headers ~body  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_api_networking_v1_network_policy.of_yojson) resp body

let watch_networking_v1_ingress_class ~sw client ~name ?allow_watch_bookmarks ?continue ?field_selector ?label_selector ?limit ?pretty ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ?watch () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/watch/ingressclasses/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.maybe_add_query_param uri "allowWatchBookmarks" string_of_bool allow_watch_bookmarks in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let uri = Request.maybe_add_query_param uri "watch" string_of_bool watch in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_watch_event.of_yojson) resp body

let watch_networking_v1_ingress_class_list ~sw client ?allow_watch_bookmarks ?continue ?field_selector ?label_selector ?limit ?pretty ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ?watch () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/watch/ingressclasses" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.maybe_add_query_param uri "allowWatchBookmarks" string_of_bool allow_watch_bookmarks in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let uri = Request.maybe_add_query_param uri "watch" string_of_bool watch in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_watch_event.of_yojson) resp body

let watch_networking_v1_ingress_list_for_all_namespaces ~sw client ?allow_watch_bookmarks ?continue ?field_selector ?label_selector ?limit ?pretty ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ?watch () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/watch/ingresses" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.maybe_add_query_param uri "allowWatchBookmarks" string_of_bool allow_watch_bookmarks in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let uri = Request.maybe_add_query_param uri "watch" string_of_bool watch in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_watch_event.of_yojson) resp body

let watch_networking_v1_namespaced_ingress ~sw client ~name ~namespace ?allow_watch_bookmarks ?continue ?field_selector ?label_selector ?limit ?pretty ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ?watch () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/watch/namespaces/{namespace}/ingresses/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "allowWatchBookmarks" string_of_bool allow_watch_bookmarks in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let uri = Request.maybe_add_query_param uri "watch" string_of_bool watch in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_watch_event.of_yojson) resp body

let watch_networking_v1_namespaced_ingress_list ~sw client ~namespace ?allow_watch_bookmarks ?continue ?field_selector ?label_selector ?limit ?pretty ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ?watch () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/watch/namespaces/{namespace}/ingresses" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "allowWatchBookmarks" string_of_bool allow_watch_bookmarks in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let uri = Request.maybe_add_query_param uri "watch" string_of_bool watch in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_watch_event.of_yojson) resp body

let watch_networking_v1_namespaced_network_policy ~sw client ~name ~namespace ?allow_watch_bookmarks ?continue ?field_selector ?label_selector ?limit ?pretty ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ?watch () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/watch/namespaces/{namespace}/networkpolicies/{name}" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "allowWatchBookmarks" string_of_bool allow_watch_bookmarks in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let uri = Request.maybe_add_query_param uri "watch" string_of_bool watch in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_watch_event.of_yojson) resp body

let watch_networking_v1_namespaced_network_policy_list ~sw client ~namespace ?allow_watch_bookmarks ?continue ?field_selector ?label_selector ?limit ?pretty ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ?watch () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/watch/namespaces/{namespace}/networkpolicies" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.replace_path_param uri "namespace" (fun x -> x) namespace in
    let uri = Request.maybe_add_query_param uri "allowWatchBookmarks" string_of_bool allow_watch_bookmarks in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let uri = Request.maybe_add_query_param uri "watch" string_of_bool watch in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_watch_event.of_yojson) resp body

let watch_networking_v1_network_policy_list_for_all_namespaces ~sw client ?allow_watch_bookmarks ?continue ?field_selector ?label_selector ?limit ?pretty ?resource_version ?resource_version_match ?send_initial_events ?timeout_seconds ?watch () =
    let uri = Request.build_uri "/apis/networking.k8s.io/v1/watch/networkpolicies" in
    let headers = Request.default_headers in
    let headers = Cohttp.Header.add headers "authorization" Request.api_key in
    let uri = Request.maybe_add_query_param uri "allowWatchBookmarks" string_of_bool allow_watch_bookmarks in
    let uri = Request.maybe_add_query_param uri "continue" (fun x -> x) continue in
    let uri = Request.maybe_add_query_param uri "fieldSelector" (fun x -> x) field_selector in
    let uri = Request.maybe_add_query_param uri "labelSelector" (fun x -> x) label_selector in
    let uri = Request.maybe_add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.maybe_add_query_param uri "pretty" (fun x -> x) pretty in
    let uri = Request.maybe_add_query_param uri "resourceVersion" (fun x -> x) resource_version in
    let uri = Request.maybe_add_query_param uri "resourceVersionMatch" (fun x -> x) resource_version_match in
    let uri = Request.maybe_add_query_param uri "sendInitialEvents" string_of_bool send_initial_events in
    let uri = Request.maybe_add_query_param uri "timeoutSeconds" Int32.to_string timeout_seconds in
    let uri = Request.maybe_add_query_param uri "watch" string_of_bool watch in
    let resp, body = Cohttp_eio.Client.call ~sw client `GET uri ~headers  in
    Request.read_json_body_as (JsonSupport.unwrap Io_k8s_apimachinery_pkg_apis_meta_v1_watch_event.of_yojson) resp body

