---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mahout-controller-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mahout.anqou.net
  resources:
  - mastodons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mahout.anqou.net
  resources:
  - mastodons/finalizers
  verbs:
  - update
- apiGroups:
  - mahout.anqou.net
  resources:
  - mastodons/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mahout-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mahout-controller-role
subjects:
- kind: ServiceAccount
  name: mahout-controller-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mahout-controller-sa
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
    - name: ubuntu
      image: mahout:dev
#     image: ubuntu:22.04
#     command:
#       - bash
#       - -c
#       - |
#         sleep infinity
      env:
        - name: OCAMLRUNPARAM
          value: b
        - name: COHTTP_DEBUG
          value: "1"
  serviceAccountName: mahout-controller-sa
---
apiVersion: mahout.anqou.net/v1alpha1
kind: Mastodon
metadata:
  name: mastodon0
spec:
  image: "ghcr.io/mastodon/mastodon:4.2.1"
  envFrom:
    - secretRef:
        name: secret-env
