---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mahout-controller-role
  namespace: default
rules:
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mahout.anqou.net
  resources:
  - mastodons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mahout.anqou.net
  resources:
  - mastodons/finalizers
  verbs:
  - update
- apiGroups:
  - mahout.anqou.net
  resources:
  - mastodons/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mahout-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mahout-controller-role
subjects:
- kind: ServiceAccount
  name: mahout-controller-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mahout-controller-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastodon-operator
  template:
    metadata:
      labels:
        app: mastodon-operator
    spec:
      containers:
        - name: ubuntu
          image: mahout:dev
          env:
            - name: OCAMLRUNPARAM
              value: b
            - name: COHTTP_DEBUG
              value: "1"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      serviceAccountName: mahout-controller-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-env
type: Opaque
stringData:
  LOCAL_DOMAIN: "mastodon0.ket-apps.test"
---
apiVersion: mahout.anqou.net/v1alpha1
kind: Mastodon
metadata:
  name: mastodon1
  namespace: default
spec:
  image: "ghcr.io/ushitora-anqou/ket-mastodon:4.2.4.1"
  envFrom:
    - secretRef:
        name: secret-env
