---
apiVersion: mahout.anqou.net/v1alpha1
kind: Mastodon
metadata:
  name: mastodon0
  namespace: e2e
spec:
  serverName: "mastodon0.ket-apps.test"
  image: "ghcr.io/mastodon/mastodon:v4.2.0"
  envFrom:
    - secretRef:
        name: secret-env
