---
apiVersion: mahout.anqou.net/v1alpha1
kind: Mastodon
metadata:
  name: mastodon0
  namespace: e2e
spec:
  serverName: "mastodon.test"
  image: "ghcr.io/mastodon/mastodon:v4.1.9"
  envFrom:
    - secretRef:
        name: secret-env
  gateway:
    replicas: 1
    annotations:
      test.mahout.anqou.net/role: gateway
    image: "nginx:1.25.4"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 100Mi
  sidekiq:
    replicas: 1
    annotations:
      test.mahout.anqou.net/role: sidekiq
  streaming:
    replicas: 1
    annotations:
      test.mahout.anqou.net/role: streaming
  web:
    replicas: 1
    annotations:
      test.mahout.anqou.net/role: web
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: "1"
        memory: 1000Mi
