---
apiVersion: mahout.anqou.net/v1alpha1
kind: Mastodon
metadata:
  name: mastodon0
spec:
  image: "ghcr.io/mastodon/mastodon:v4.1.9"
  envFrom:
    - secretRef:
        name: secret-env
  gateway:
    nginxConfTemplateConfigMap: gateway-nginx-conf-template
