(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_component_condition.t : Information about the condition of a component.
 *)

[@@@warning "-32-34"]
open (struct
    include Ppx_yojson_conv_lib.Yojson_conv.Primitives
    type any = Yojson.Safe.t
    let any_of_yojson = Fun.id
    let yojson_of_any = Fun.id
    let pp_any = Yojson.Safe.pp
    let show_any = Yojson.Safe.show
    let string_of_yojson = function
      | `String s -> s
      | `Int i -> string_of_int i
      | _ -> failwith "string_of_yojson: string or int needed"
end)
type t = {
    (* Condition error code for a component. For example, a health check error code. *)
    error: string option [@yojson.default None] [@yojson.key "error"];
    (* Message about the condition for a component. For example, information about a health check. *)
    message: string option [@yojson.default None] [@yojson.key "message"];
    (* Status of the condition for a component. Valid values for \''Healthy\'': \''True\'', \''False\'', or \''Unknown\''. *)
    status: string [@yojson.key "status"];
    (* Type of condition for a component. Valid value: \''Healthy\'' *)
    _type: string [@yojson.key "type"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson x =
  try
    Ok (t_of_yojson x)
  with
  | Ppx_yojson_conv_lib.Yojson_conv.Of_yojson_error (e, j) ->
      Error (Printf.sprintf "%s: %s" (Printexc.to_string e) (Yojson.Safe.to_string j))


