(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_batch_v1_job_status.t : JobStatus represents the current state of a Job.
 *)

[@@@warning "-32-34"]
open (struct
    include Ppx_yojson_conv_lib.Yojson_conv.Primitives
    type any = Yojson.Safe.t
    let any_of_yojson = Fun.id
    let yojson_of_any = Fun.id
    let pp_any = Yojson.Safe.pp
    let show_any = Yojson.Safe.show
    let string_of_yojson = function
      | `String s -> s
      | `Int i -> string_of_int i
      | _ -> failwith "string_of_yojson: string or int needed"
end)
type t = {
    (* The number of pending and running pods which are not terminating (without a deletionTimestamp). The value is zero for finished jobs. *)
    active: int32 option [@yojson.default None] [@yojson.key "active"];
    (* completedIndexes holds the completed indexes when .spec.completionMode = \''Indexed\'' in a text format. The indexes are represented as decimal integers separated by commas. The numbers are listed in increasing order. Three or more consecutive numbers are compressed and represented by the first and last element of the series, separated by a hyphen. For example, if the completed indexes are 1, 3, 4, 5 and 7, they are represented as \''1,3-5,7\''. *)
    completed_indexes: string option [@yojson.default None] [@yojson.key "completedIndexes"];
    (* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. *)
    completion_time: string option [@yojson.default None] [@yojson.key "completionTime"];
    (* The latest available observations of an object's current state. When a Job fails, one of the conditions will have type \''Failed\'' and status true. When a Job is suspended, one of the conditions will have type \''Suspended\'' and status true; when the Job is resumed, the status of this condition will become false. When a Job is completed, one of the conditions will have type \''Complete\'' and status true.  A job is considered finished when it is in a terminal condition, either \''Complete\'' or \''Failed\''. A Job cannot have both the \''Complete\'' and \''Failed\'' conditions. Additionally, it cannot be in the \''Complete\'' and \''FailureTarget\'' conditions. The \''Complete\'', \''Failed\'' and \''FailureTarget\'' conditions cannot be disabled.  More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/ *)
    conditions: Io_k8s_api_batch_v1_job_condition.t list [@default []] [@yojson.key "conditions"];
    (* The number of pods which reached phase Failed. The value increases monotonically. *)
    failed: int32 option [@yojson.default None] [@yojson.key "failed"];
    (* FailedIndexes holds the failed indexes when spec.backoffLimitPerIndex is set. The indexes are represented in the text format analogous as for the `completedIndexes` field, ie. they are kept as decimal integers separated by commas. The numbers are listed in increasing order. Three or more consecutive numbers are compressed and represented by the first and last element of the series, separated by a hyphen. For example, if the failed indexes are 1, 3, 4, 5 and 7, they are represented as \''1,3-5,7\''. The set of failed indexes cannot overlap with the set of completed indexes.  This field is beta-level. It can be used when the `JobBackoffLimitPerIndex` feature gate is enabled (enabled by default). *)
    failed_indexes: string option [@yojson.default None] [@yojson.key "failedIndexes"];
    (* The number of pods which have a Ready condition. *)
    ready: int32 option [@yojson.default None] [@yojson.key "ready"];
    (* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. *)
    start_time: string option [@yojson.default None] [@yojson.key "startTime"];
    (* The number of pods which reached phase Succeeded. The value increases monotonically for a given spec. However, it may decrease in reaction to scale down of elastic indexed jobs. *)
    succeeded: int32 option [@yojson.default None] [@yojson.key "succeeded"];
    (* The number of pods which are terminating (in phase Pending or Running and have a deletionTimestamp).  This field is beta-level. The job controller populates the field when the feature gate JobPodReplacementPolicy is enabled (enabled by default). *)
    terminating: int32 option [@yojson.default None] [@yojson.key "terminating"];
    uncounted_terminated_pods: Io_k8s_api_batch_v1_uncounted_terminated_pods.t option [@yojson.default None] [@yojson.key "uncountedTerminatedPods"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson x =
  try
    Ok (t_of_yojson x)
  with
  | Ppx_yojson_conv_lib.Yojson_conv.Of_yojson_error (e, j) ->
      Error (Printf.sprintf "%s: %s" (Printexc.to_string e) (Yojson.Safe.to_string j))


