apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mahout.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mahout.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mahout.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mahout.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mahout.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - controller
            - --gw-nginx-conf-templ-cm
            - {{ include "mahout.fullname" . }}-gateway-nginx-conf-template
          imagePullPolicy: {{ .Values.image.pullPolicy }}
#         ports:
#           - name: http
#             containerPort: {{ .Values.service.port }}
#             protocol: TCP
#         livenessProbe:
#           httpGet:
#             path: /healthz
#             port: http
#         readinessProbe:
#           httpGet:
#             path: /readyz
#             port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: OCAMLRUNPARAM
              value: b
            - name: COHTTP_DEBUG
              value: "1"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
