(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_authorization_v1_resource_attributes.t : ResourceAttributes includes the authorization attributes available for resource requests to the Authorizer interface
 *)

open Ppx_yojson_conv_lib.Yojson_conv.Primitives
type t = {
    (* Group is the API Group of the Resource.  \''*\'' means all. *)
    group: string option [@yojson.default None] [@yojson.key "group"];
    (* Name is the name of the resource being requested for a \''get\'' or deleted for a \''delete\''. \''\'' (empty) means all. *)
    name: string option [@yojson.default None] [@yojson.key "name"];
    (* Namespace is the namespace of the action being requested.  Currently, there is no distinction between no namespace and all namespaces \''\'' (empty) is defaulted for LocalSubjectAccessReviews \''\'' (empty) is empty for cluster-scoped resources \''\'' (empty) means \''all\'' for namespace scoped resources from a SubjectAccessReview or SelfSubjectAccessReview *)
    namespace: string option [@yojson.default None] [@yojson.key "namespace"];
    (* Resource is one of the existing resource types.  \''*\'' means all. *)
    resource: string option [@yojson.default None] [@yojson.key "resource"];
    (* Subresource is one of the existing resource types.  \''\'' means none. *)
    subresource: string option [@yojson.default None] [@yojson.key "subresource"];
    (* Verb is a kubernetes resource API verb, like: get, list, watch, create, update, delete, proxy.  \''*\'' means all. *)
    verb: string option [@yojson.default None] [@yojson.key "verb"];
    (* Version is the API Version of the Resource.  \''*\'' means all. *)
    version: string option [@yojson.default None] [@yojson.key "version"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson = t_of_yojson


