(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_config_map_key_selector.t : Selects a key from a ConfigMap.
 *)

type t = {
    (* The key to select. *)
    key: string [@yojson.key "key"];
    (* Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names *)
    name: string option [@yojson.default None] [@yojson.key "name"];
    (* Specify whether the ConfigMap or its key must be defined *)
    optional: bool option [@yojson.default None] [@yojson.key "optional"];
} [@@deriving yojson { strict = false }, show, make];;


