(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_resource_v1alpha2_resource_claim_consumer_reference.t : ResourceClaimConsumerReference contains enough information to let you locate the consumer of a ResourceClaim. The user must be a resource in the same namespace as the ResourceClaim.
 *)

type t = {
    (* APIGroup is the group for the resource being referenced. It is empty for the core API. This matches the group in the APIVersion that is used when creating the resources. *)
    api_group: string option [@default None] [@key apiGroup];
    (* Name is the name of resource being referenced. *)
    name: string [@key name];
    (* Resource is the type of resource being referenced, for example \''pods\''. *)
    resource: string [@key resource];
    (* UID identifies exactly one incarnation of the resource. *)
    uid: string [@key uid];
} [@@deriving yojson { strict = false }, show ];;

(** ResourceClaimConsumerReference contains enough information to let you locate the consumer of a ResourceClaim. The user must be a resource in the same namespace as the ResourceClaim. *)
let create (name : string) (resource : string) (uid : string) : t = {
    api_group = None;
    name = name;
    resource = resource;
    uid = uid;
}

