(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_container_state_terminated.t : ContainerStateTerminated is a terminated state of a container.
 *)

type t = {
    (* Container's ID in the format '<type>://<container_id>' *)
    container_id: string option [@default None];
    (* Exit status from the last termination of the container *)
    exit_code: int32;
    (* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. *)
    finished_at: string option [@default None];
    (* Message regarding the last termination of the container *)
    message: string option [@default None];
    (* (brief) reason from the last termination of the container *)
    reason: string option [@default None];
    (* Signal from the last termination of the container *)
    signal: int32 option [@default None];
    (* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. *)
    started_at: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** ContainerStateTerminated is a terminated state of a container. *)
let create (exit_code : int32) : t = {
    container_id = None;
    exit_code = exit_code;
    finished_at = None;
    message = None;
    reason = None;
    signal = None;
    started_at = None;
}

