(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_apps_v1_daemon_set_status.t : DaemonSetStatus represents the current status of a daemon set.
 *)

[@@@warning "-32-34"]
open (struct
    include Ppx_yojson_conv_lib.Yojson_conv.Primitives
    type any = Yojson.Safe.t
    let any_of_yojson = Fun.id
    let yojson_of_any = Fun.id
    let pp_any = Yojson.Safe.pp
    let show_any = Yojson.Safe.show
    let string_of_yojson = function
      | `String s -> s
      | `Int i -> string_of_int i
      | _ -> failwith "string_of_yojson: string or int needed"
end)
type t = {
    (* Count of hash collisions for the DaemonSet. The DaemonSet controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ControllerRevision. *)
    collision_count: int32 option [@yojson.default None] [@yojson.key "collisionCount"];
    (* Represents the latest available observations of a DaemonSet's current state. *)
    conditions: Io_k8s_api_apps_v1_daemon_set_condition.t list [@default []] [@yojson.key "conditions"];
    (* The number of nodes that are running at least 1 daemon pod and are supposed to run the daemon pod. More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ *)
    current_number_scheduled: int32 [@yojson.key "currentNumberScheduled"];
    (* The total number of nodes that should be running the daemon pod (including nodes correctly running the daemon pod). More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ *)
    desired_number_scheduled: int32 [@yojson.key "desiredNumberScheduled"];
    (* The number of nodes that should be running the daemon pod and have one or more of the daemon pod running and available (ready for at least spec.minReadySeconds) *)
    number_available: int32 option [@yojson.default None] [@yojson.key "numberAvailable"];
    (* The number of nodes that are running the daemon pod, but are not supposed to run the daemon pod. More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ *)
    number_misscheduled: int32 [@yojson.key "numberMisscheduled"];
    (* numberReady is the number of nodes that should be running the daemon pod and have one or more of the daemon pod running with a Ready Condition. *)
    number_ready: int32 [@yojson.key "numberReady"];
    (* The number of nodes that should be running the daemon pod and have none of the daemon pod running and available (ready for at least spec.minReadySeconds) *)
    number_unavailable: int32 option [@yojson.default None] [@yojson.key "numberUnavailable"];
    (* The most recent generation observed by the daemon set controller. *)
    observed_generation: int64 option [@yojson.default None] [@yojson.key "observedGeneration"];
    (* The total number of nodes that are running updated daemon pod *)
    updated_number_scheduled: int32 option [@yojson.default None] [@yojson.key "updatedNumberScheduled"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson x =
  try
    Ok (t_of_yojson x)
  with
  | Ppx_yojson_conv_lib.Yojson_conv.Of_yojson_error (e, j) ->
      Error (Printf.sprintf "%s: %s" (Printexc.to_string e) (Yojson.Safe.to_string j))


