(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_env_from_source.t : EnvFromSource represents the source of a set of ConfigMaps
 *)

type t = {
    config_map_ref: Io_k8s_api_core_v1_config_map_env_source.t option [@yojson.default None] [@yojson.key "configMapRef"];
    (* An optional identifier to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER. *)
    prefix: string option [@yojson.default None] [@yojson.key "prefix"];
    secret_ref: Io_k8s_api_core_v1_secret_env_source.t option [@yojson.default None] [@yojson.key "secretRef"];
} [@@deriving yojson { strict = false }, show, make];;


