(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_node_config_source.t : NodeConfigSource specifies a source of node configuration. Exactly one subfield (excluding metadata) must be non-nil. This API is deprecated since 1.22
 *)

type t = {
    config_map: Io_k8s_api_core_v1_config_map_node_config_source.t option [@yojson.default None] [@yojson.key "configMap"];
} [@@deriving yojson { strict = false }, show, make];;


