(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_node_selector_term.t : A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.
 *)

open Ppx_yojson_conv_lib.Yojson_conv.Primitives
type t = {
    (* A list of node selector requirements by node's labels. *)
    match_expressions: Io_k8s_api_core_v1_node_selector_requirement.t list [@yojson.default []] [@yojson.key "matchExpressions"];
    (* A list of node selector requirements by node's fields. *)
    match_fields: Io_k8s_api_core_v1_node_selector_requirement.t list [@yojson.default []] [@yojson.key "matchFields"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson = t_of_yojson


