(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_apps_v1_stateful_set_spec.t : A StatefulSetSpec is the specification of a StatefulSet.
 *)

type t = {
    (* Minimum number of seconds for which a newly created pod should be ready without any of its container crashing for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready) *)
    min_ready_seconds: int32 option [@default None];
    ordinals: Io_k8s_api_apps_v1_stateful_set_ordinals.t option [@default None];
    persistent_volume_claim_retention_policy: Io_k8s_api_apps_v1_stateful_set_persistent_volume_claim_retention_policy.t option [@default None];
    (* podManagementPolicy controls how pods are created during initial scale up, when replacing pods on nodes, or when scaling down. The default policy is `OrderedReady`, where pods are created in increasing order (pod-0, then pod-1, etc) and the controller will wait until each pod is ready before continuing. When scaling down, the pods are removed in the opposite order. The alternative policy is `Parallel` which will create pods in parallel to match the desired scale without waiting, and on scale down will delete all pods at once. *)
    pod_management_policy: string option [@default None];
    (* replicas is the desired number of replicas of the given Template. These are replicas in the sense that they are instantiations of the same Template, but individual replicas also have a consistent identity. If unspecified, defaults to 1. *)
    replicas: int32 option [@default None];
    (* revisionHistoryLimit is the maximum number of revisions that will be maintained in the StatefulSet's revision history. The revision history consists of all revisions not represented by a currently applied StatefulSetSpec version. The default value is 10. *)
    revision_history_limit: int32 option [@default None];
    selector: Io_k8s_apimachinery_pkg_apis_meta_v1_label_selector.t;
    (* serviceName is the name of the service that governs this StatefulSet. This service must exist before the StatefulSet, and is responsible for the network identity of the set. Pods get DNS/hostnames that follow the pattern: pod-specific-string.serviceName.default.svc.cluster.local where \''pod-specific-string\'' is managed by the StatefulSet controller. *)
    service_name: string;
    template: Io_k8s_api_core_v1_pod_template_spec.t;
    update_strategy: Io_k8s_api_apps_v1_stateful_set_update_strategy.t option [@default None];
    (* volumeClaimTemplates is a list of claims that pods are allowed to reference. The StatefulSet controller is responsible for mapping network identities to claims in a way that maintains the identity of a pod. Every claim in this list must have at least one matching (by name) volumeMount in one container in the template. A claim in this list takes precedence over any volumes in the template, with the same name. *)
    volume_claim_templates: Io_k8s_api_core_v1_persistent_volume_claim.t list;
} [@@deriving yojson { strict = false }, show ];;

(** A StatefulSetSpec is the specification of a StatefulSet. *)
let create (selector : Io_k8s_apimachinery_pkg_apis_meta_v1_label_selector.t) (service_name : string) (template : Io_k8s_api_core_v1_pod_template_spec.t) : t = {
    min_ready_seconds = None;
    ordinals = None;
    persistent_volume_claim_retention_policy = None;
    pod_management_policy = None;
    replicas = None;
    revision_history_limit = None;
    selector = selector;
    service_name = service_name;
    template = template;
    update_strategy = None;
    volume_claim_templates = [];
}

