(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_taint.t : The node this Taint is attached to has the \''effect\'' on any pod that does not tolerate the Taint.
 *)

open Ppx_yojson_conv_lib.Yojson_conv.Primitives
type t = {
    (* Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute. *)
    effect: string [@yojson.key "effect"];
    (* Required. The taint key to be applied to a node. *)
    key: string [@yojson.key "key"];
    (* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. *)
    time_added: string option [@yojson.default None] [@yojson.key "timeAdded"];
    (* The taint value corresponding to the taint key. *)
    value: string option [@yojson.default None] [@yojson.key "value"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson = t_of_yojson


