(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_authentication_v1_bound_object_reference.t : BoundObjectReference is a reference to an object that a token is bound to.
 *)

type t = {
    (* API version of the referent. *)
    api_version: string option [@yojson.default None] [@yojson.key "apiVersion"];
    (* Kind of the referent. Valid kinds are 'Pod' and 'Secret'. *)
    kind: string option [@yojson.default None] [@yojson.key "kind"];
    (* Name of the referent. *)
    name: string option [@yojson.default None] [@yojson.key "name"];
    (* UID of the referent. *)
    uid: string option [@yojson.default None] [@yojson.key "uid"];
} [@@deriving yojson { strict = false }, show, make];;


