(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_load_balancer_ingress.t : LoadBalancerIngress represents the status of a load-balancer ingress point: traffic intended for the service should be sent to an ingress point.
 *)

open Ppx_yojson_conv_lib.Yojson_conv.Primitives
type t = {
    (* Hostname is set for load-balancer ingress points that are DNS based (typically AWS load-balancers) *)
    hostname: string option [@yojson.default None] [@yojson.key "hostname"];
    (* IP is set for load-balancer ingress points that are IP based (typically GCE or OpenStack load-balancers) *)
    ip: string option [@yojson.default None] [@yojson.key "ip"];
    (* Ports is a list of records of service ports If used, every port defined in the service should have an entry in it *)
    ports: Io_k8s_api_core_v1_port_status.t list [@yojson.default []] [@yojson.key "ports"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson = t_of_yojson


