(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_apps_v1_daemon_set_spec.t : DaemonSetSpec is the specification of a daemon set.
 *)

type t = {
    (* The minimum number of seconds for which a newly created DaemonSet pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready). *)
    min_ready_seconds: int32 option [@default None];
    (* The number of old history to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 10. *)
    revision_history_limit: int32 option [@default None];
    selector: Io_k8s_apimachinery_pkg_apis_meta_v1_label_selector.t;
    template: Io_k8s_api_core_v1_pod_template_spec.t;
    update_strategy: Io_k8s_api_apps_v1_daemon_set_update_strategy.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** DaemonSetSpec is the specification of a daemon set. *)
let create (selector : Io_k8s_apimachinery_pkg_apis_meta_v1_label_selector.t) (template : Io_k8s_api_core_v1_pod_template_spec.t) : t = {
    min_ready_seconds = None;
    revision_history_limit = None;
    selector = selector;
    template = template;
    update_strategy = None;
}

