(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1_service_reference.t : ServiceReference holds a reference to Service.legacy.k8s.io
 *)

type t = {
    (* name is the name of the service. Required *)
    name: string [@yojson.key "name"];
    (* namespace is the namespace of the service. Required *)
    namespace: string [@yojson.key "namespace"];
    (* path is an optional URL path at which the webhook will be contacted. *)
    path: string option [@yojson.default None] [@yojson.key "path"];
    (* port is an optional service port at which the webhook will be contacted. `port` should be a valid port number (1-65535, inclusive). Defaults to 443 for backward compatibility. *)
    port: int32 option [@yojson.default None] [@yojson.key "port"];
} [@@deriving yojson { strict = false }, show, make];;


