(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_ephemeral_volume_source.t : Represents an ephemeral volume that is handled by a normal storage driver.
 *)

type t = {
    volume_claim_template: Io_k8s_api_core_v1_persistent_volume_claim_template.t option [@yojson.default None] [@yojson.key "volumeClaimTemplate"];
} [@@deriving yojson { strict = false }, show, make];;


