(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_resource_quota_spec.t : ResourceQuotaSpec defines the desired hard limits to enforce for Quota.
 *)

type t = {
    (* hard is the set of desired hard limits for each named resource. More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/ *)
    hard: Yojson.Safe.t [@yojson.default (`List [])] [@yojson.key "hard"];
    scope_selector: Io_k8s_api_core_v1_scope_selector.t option [@yojson.default None] [@yojson.key "scopeSelector"];
    (* A collection of filters that must match each object tracked by a quota. If not specified, the quota matches all objects. *)
    scopes: string list [@yojson.default []] [@yojson.key "scopes"];
} [@@deriving yojson { strict = false }, show, make];;


