(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_tcp_socket_action.t : TCPSocketAction describes an action based on opening a socket
 *)

type t = {
    (* Optional: Host name to connect to, defaults to the pod IP. *)
    host: string option [@default None] [@key "host"];
    (* IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number. *)
    port: string [@key "port"];
} [@@deriving yojson { strict = false }, show ];;

(** TCPSocketAction describes an action based on opening a socket *)
let create (port : string) : t = {
    host = None;
    port = port;
}

