(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_photon_persistent_disk_volume_source.t : Represents a Photon Controller persistent disk resource.
 *)

type t = {
    (* fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \''ext4\'', \''xfs\'', \''ntfs\''. Implicitly inferred to be \''ext4\'' if unspecified. *)
    fs_type: string option [@yojson.default None] [@yojson.key "fsType"];
    (* pdID is the ID that identifies Photon Controller persistent disk *)
    pd_id: string [@yojson.key "pdID"];
} [@@deriving yojson { strict = false }, show, make];;


