(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_topology_selector_term.t : A topology selector term represents the result of label queries. A null or empty topology selector term matches no objects. The requirements of them are ANDed. It provides a subset of functionality as NodeSelectorTerm. This is an alpha feature and may change in the future.
 *)

open Ppx_yojson_conv_lib.Yojson_conv.Primitives
type t = {
    (* A list of topology selector requirements by labels. *)
    match_label_expressions: Io_k8s_api_core_v1_topology_selector_label_requirement.t list [@yojson.default []] [@yojson.key "matchLabelExpressions"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson = t_of_yojson


