(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_apiserverinternal_v1alpha1_storage_version_condition.t : Describes the state of the storageVersion at a certain point.
 *)

type t = {
    (* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. *)
    last_transition_time: string option [@yojson.default None] [@yojson.key "lastTransitionTime"];
    (* A human readable message indicating details about the transition. *)
    message: string option [@yojson.default None] [@yojson.key "message"];
    (* If set, this represents the .metadata.generation that the condition was set based upon. *)
    observed_generation: int64 option [@yojson.default None] [@yojson.key "observedGeneration"];
    (* The reason for the condition's last transition. *)
    reason: string [@yojson.key "reason"];
    (* Status of the condition, one of True, False, Unknown. *)
    status: string [@yojson.key "status"];
    (* Type of the condition. *)
    _type: string [@yojson.key "type"];
} [@@deriving yojson { strict = false }, show, make];;


