(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_networking_v1_ingress_port_status.t : IngressPortStatus represents the error condition of a service port
 *)

type t = {
    (* error is to record the problem with the service port The format of the error shall comply with the following rules: - built-in error values shall be specified in this file and those shall use   CamelCase names - cloud provider specific error values must have names that comply with the   format foo.example.com/CamelCase. *)
    error: string option [@default None] [@key error];
    (* port is the port number of the ingress port. *)
    port: int32 [@key port];
    (* protocol is the protocol of the ingress port. The supported values are: \''TCP\'', \''UDP\'', \''SCTP\'' *)
    protocol: string [@key protocol];
} [@@deriving yojson { strict = false }, show ];;

(** IngressPortStatus represents the error condition of a service port *)
let create (port : int32) (protocol : string) : t = {
    error = None;
    port = port;
    protocol = protocol;
}

