(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_apiserverinternal_v1alpha1_storage_version_status.t : API server instances report the versions they can decode and the version they encode objects to when persisting objects in the backend.
 *)

open Ppx_yojson_conv_lib.Yojson_conv.Primitives
type t = {
    (* If all API server instances agree on the same encoding storage version, then this field is set to that version. Otherwise this field is left empty. API servers should finish updating its storageVersionStatus entry before serving write operations, so that this field will be in sync with the reality. *)
    common_encoding_version: string option [@yojson.default None] [@yojson.key "commonEncodingVersion"];
    (* The latest available observations of the storageVersion's state. *)
    conditions: Io_k8s_api_apiserverinternal_v1alpha1_storage_version_condition.t list [@yojson.default []] [@yojson.key "conditions"];
    (* The reported versions per API server instance. *)
    storage_versions: Io_k8s_api_apiserverinternal_v1alpha1_server_storage_version.t list [@yojson.default []] [@yojson.key "storageVersions"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson = t_of_yojson


