(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_pod_condition.t : PodCondition contains details for the current condition of this pod.
 *)

type t = {
    (* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. *)
    last_probe_time: string option [@default None];
    (* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. *)
    last_transition_time: string option [@default None];
    (* Human-readable message indicating details about last transition. *)
    message: string option [@default None];
    (* Unique, one-word, CamelCase reason for the condition's last transition. *)
    reason: string option [@default None];
    (* Status is the status of the condition. Can be True, False, Unknown. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions *)
    status: string;
    (* Type is the type of the condition. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions *)
    _type: string; [@key "type"]
} [@@deriving yojson { strict = false }, show ];;

(** PodCondition contains details for the current condition of this pod. *)
let create (status : string) (_type : string) : t = {
    last_probe_time = None;
    last_transition_time = None;
    message = None;
    reason = None;
    status = status;
    _type = _type;
}

