(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_lifecycle_handler.t : LifecycleHandler defines a specific action that should be taken in a lifecycle hook. One and only one of the fields, except TCPSocket must be specified.
 *)

type t = {
    exec: Io_k8s_api_core_v1_exec_action.t option [@default None];
    http_get: Io_k8s_api_core_v1_http_get_action.t option [@default None];
    tcp_socket: Io_k8s_api_core_v1_tcp_socket_action.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** LifecycleHandler defines a specific action that should be taken in a lifecycle hook. One and only one of the fields, except TCPSocket must be specified. *)
let create () : t = {
    exec = None;
    http_get = None;
    tcp_socket = None;
}

