(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_node_condition.t : NodeCondition contains condition information for a node.
 *)

type t = {
    (* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. *)
    last_heartbeat_time: string option [@default None] [@key "lastHeartbeatTime"];
    (* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. *)
    last_transition_time: string option [@default None] [@key "lastTransitionTime"];
    (* Human readable message indicating details about last transition. *)
    message: string option [@default None] [@key "message"];
    (* (brief) reason for the condition's last transition. *)
    reason: string option [@default None] [@key "reason"];
    (* Status of the condition, one of True, False, Unknown. *)
    status: string [@key "status"];
    (* Type of node condition. *)
    _type: string [@key "type"];
} [@@deriving yojson { strict = false }, show ];;

(** NodeCondition contains condition information for a node. *)
let create (status : string) (_type : string) : t = {
    last_heartbeat_time = None;
    last_transition_time = None;
    message = None;
    reason = None;
    status = status;
    _type = _type;
}

