(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_authorization_v1_subject_access_review_spec.t : SubjectAccessReviewSpec is a description of the access request.  Exactly one of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes must be set
 *)

type t = {
    (* Extra corresponds to the user.Info.GetExtra() method from the authenticator.  Since that is input to the authorizer it needs a reflection here. *)
    extra: Yojson.Safe.t [@yojson.default (`List [])] [@yojson.key "extra"];
    (* Groups is the groups you're testing for. *)
    groups: string list [@yojson.default []] [@yojson.key "groups"];
    non_resource_attributes: Io_k8s_api_authorization_v1_non_resource_attributes.t option [@yojson.default None] [@yojson.key "nonResourceAttributes"];
    resource_attributes: Io_k8s_api_authorization_v1_resource_attributes.t option [@yojson.default None] [@yojson.key "resourceAttributes"];
    (* UID information about the requesting user. *)
    uid: string option [@yojson.default None] [@yojson.key "uid"];
    (* User is the user you're testing for. If you specify \''User\'' but not \''Groups\'', then is it interpreted as \''What if User were not a member of any groups *)
    user: string option [@yojson.default None] [@yojson.key "user"];
} [@@deriving yojson { strict = false }, show, make];;


