(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_csi_persistent_volume_source.t : Represents storage that is managed by an external CSI volume driver (Beta feature)
 *)

open Ppx_yojson_conv_lib.Yojson_conv.Primitives
type t = {
    controller_expand_secret_ref: Io_k8s_api_core_v1_secret_reference.t option [@yojson.default None] [@yojson.key "controllerExpandSecretRef"];
    controller_publish_secret_ref: Io_k8s_api_core_v1_secret_reference.t option [@yojson.default None] [@yojson.key "controllerPublishSecretRef"];
    (* driver is the name of the driver to use for this volume. Required. *)
    driver: string [@yojson.key "driver"];
    (* fsType to mount. Must be a filesystem type supported by the host operating system. Ex. \''ext4\'', \''xfs\'', \''ntfs\''. *)
    fs_type: string option [@yojson.default None] [@yojson.key "fsType"];
    node_expand_secret_ref: Io_k8s_api_core_v1_secret_reference.t option [@yojson.default None] [@yojson.key "nodeExpandSecretRef"];
    node_publish_secret_ref: Io_k8s_api_core_v1_secret_reference.t option [@yojson.default None] [@yojson.key "nodePublishSecretRef"];
    node_stage_secret_ref: Io_k8s_api_core_v1_secret_reference.t option [@yojson.default None] [@yojson.key "nodeStageSecretRef"];
    (* readOnly value to pass to ControllerPublishVolumeRequest. Defaults to false (read/write). *)
    read_only: bool option [@yojson.default None] [@yojson.key "readOnly"];
    (* volumeAttributes of the volume to publish. *)
    volume_attributes: Yojson.Safe.t [@yojson.default (`List [])] [@yojson.key "volumeAttributes"];
    (* volumeHandle is the unique volume name returned by the CSI volume plugin’s CreateVolume to refer to the volume on all subsequent calls. Required. *)
    volume_handle: string [@yojson.key "volumeHandle"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson = t_of_yojson


