(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_taint.t : The node this Taint is attached to has the \''effect\'' on any pod that does not tolerate the Taint.
 *)

type t = {
    (* Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute. *)
    effect: string [@key effect];
    (* Required. The taint key to be applied to a node. *)
    key: string [@key key];
    (* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. *)
    time_added: string option [@default None] [@key timeAdded];
    (* The taint value corresponding to the taint key. *)
    value: string option [@default None] [@key value];
} [@@deriving yojson { strict = false }, show ];;

(** The node this Taint is attached to has the \''effect\'' on any pod that does not tolerate the Taint. *)
let create (effect : string) (key : string) : t = {
    effect = effect;
    key = key;
    time_added = None;
    value = None;
}

