(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_storage_v1_storage_class.t : StorageClass describes the parameters for a class of storage for which PersistentVolumes can be dynamically provisioned.  StorageClasses are non-namespaced; the name of the storage class according to etcd is in ObjectMeta.Name.
 *)

type t = {
    (* allowVolumeExpansion shows whether the storage class allow volume expand. *)
    allow_volume_expansion: bool option [@default None] [@key allowVolumeExpansion];
    (* allowedTopologies restrict the node topologies where volumes can be dynamically provisioned. Each volume plugin defines its own supported topology specifications. An empty TopologySelectorTerm list means there is no topology restriction. This field is only honored by servers that enable the VolumeScheduling feature. *)
    allowed_topologies: Io_k8s_api_core_v1_topology_selector_term.t list [@default []] [@key allowedTopologies];
    (* APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources *)
    api_version: string option [@default None] [@key apiVersion];
    (* Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds *)
    kind: string option [@default None] [@key kind];
    metadata: Io_k8s_apimachinery_pkg_apis_meta_v1_object_meta.t option [@default None] [@key metadata];
    (* mountOptions controls the mountOptions for dynamically provisioned PersistentVolumes of this storage class. e.g. [\''ro\'', \''soft\'']. Not validated - mount of the PVs will simply fail if one is invalid. *)
    mount_options: string list [@default []] [@key mountOptions];
    (* parameters holds the parameters for the provisioner that should create volumes of this storage class. *)
    parameters: Yojson.Safe.t [@key parameters];
    (* provisioner indicates the type of the provisioner. *)
    provisioner: string [@key provisioner];
    (* reclaimPolicy controls the reclaimPolicy for dynamically provisioned PersistentVolumes of this storage class. Defaults to Delete. *)
    reclaim_policy: string option [@default None] [@key reclaimPolicy];
    (* volumeBindingMode indicates how PersistentVolumeClaims should be provisioned and bound.  When unset, VolumeBindingImmediate is used. This field is only honored by servers that enable the VolumeScheduling feature. *)
    volume_binding_mode: string option [@default None] [@key volumeBindingMode];
} [@@deriving yojson { strict = false }, show ];;

(** StorageClass describes the parameters for a class of storage for which PersistentVolumes can be dynamically provisioned.  StorageClasses are non-namespaced; the name of the storage class according to etcd is in ObjectMeta.Name. *)
let create (provisioner : string) : t = {
    allow_volume_expansion = None;
    allowed_topologies = [];
    api_version = None;
    kind = None;
    metadata = None;
    mount_options = [];
    parameters = `List [];
    provisioner = provisioner;
    reclaim_policy = None;
    volume_binding_mode = None;
}

