(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_networking_v1_ingress_status.t : IngressStatus describe the current state of the Ingress.
 *)

type t = {
    load_balancer: Io_k8s_api_networking_v1_ingress_load_balancer_status.t option [@default None] [@key loadBalancer];
} [@@deriving yojson { strict = false }, show ];;

(** IngressStatus describe the current state of the Ingress. *)
let create () : t = {
    load_balancer = None;
}

