(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_typed_local_object_reference.t : TypedLocalObjectReference contains enough information to let you locate the typed referenced object inside the same namespace.
 *)

type t = {
    (* APIGroup is the group for the resource being referenced. If APIGroup is not specified, the specified Kind must be in the core API group. For any other third-party types, APIGroup is required. *)
    api_group: string option [@default None];
    (* Kind is the type of resource being referenced *)
    kind: string;
    (* Name is the name of resource being referenced *)
    name: string;
} [@@deriving yojson { strict = false }, show ];;

(** TypedLocalObjectReference contains enough information to let you locate the typed referenced object inside the same namespace. *)
let create (kind : string) (name : string) : t = {
    api_group = None;
    kind = kind;
    name = name;
}

