(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_container_resize_policy.t : ContainerResizePolicy represents resource resize policy for the container.
 *)

type t = {
    (* Name of the resource to which this resource resize policy applies. Supported values: cpu, memory. *)
    resource_name: string [@yojson.key "resourceName"];
    (* Restart policy to apply when specified resource is resized. If not specified, it defaults to NotRequired. *)
    restart_policy: string [@yojson.key "restartPolicy"];
} [@@deriving yojson { strict = false }, show, make];;


