(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_autoscaling_v2_hpa_scaling_policy.t : HPAScalingPolicy is a single policy which must hold true for a specified past interval.
 *)

type t = {
    (* periodSeconds specifies the window of time for which the policy should hold true. PeriodSeconds must be greater than zero and less than or equal to 1800 (30 min). *)
    period_seconds: int32;
    (* type is used to specify the scaling policy. *)
    _type: string;
    (* value contains the amount of change which is permitted by the policy. It must be greater than zero *)
    value: int32;
} [@@deriving yojson { strict = false }, show ];;

(** HPAScalingPolicy is a single policy which must hold true for a specified past interval. *)
let create (period_seconds : int32) (_type : string) (value : int32) : t = {
    period_seconds = period_seconds;
    _type = _type;
    value = value;
}

