(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_admissionregistration_v1_service_reference.t : ServiceReference holds a reference to Service.legacy.k8s.io
 *)

type t = {
    (* `name` is the name of the service. Required *)
    name: string;
    (* `namespace` is the namespace of the service. Required *)
    namespace: string;
    (* `path` is an optional URL path which will be sent in any request to this service. *)
    path: string option [@default None];
    (* If specified, the port on the service that hosting webhook. Default to 443 for backward compatibility. `port` should be a valid port number (1-65535, inclusive). *)
    port: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** ServiceReference holds a reference to Service.legacy.k8s.io *)
let create (name : string) (namespace : string) : t = {
    name = name;
    namespace = namespace;
    path = None;
    port = None;
}

