(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_apimachinery_pkg_apis_meta_v1_group_version_for_discovery.t : GroupVersion contains the \''group/version\'' and \''version\'' string of a version. It is made a struct to keep extensibility.
 *)

type t = {
    (* groupVersion specifies the API group and version in the form \''group/version\'' *)
    group_version: string [@key "groupVersion"];
    (* version specifies the version in the form of \''version\''. This is to save the clients the trouble of splitting the GroupVersion. *)
    version: string [@key "version"];
} [@@deriving yojson { strict = false }, show ];;

(** GroupVersion contains the \''group/version\'' and \''version\'' string of a version. It is made a struct to keep extensibility. *)
let create (group_version : string) (version : string) : t = {
    group_version = group_version;
    version = version;
}

