(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_kube_aggregator_pkg_apis_apiregistration_v1_service_reference.t : ServiceReference holds a reference to Service.legacy.k8s.io
 *)

type t = {
    (* Name is the name of the service *)
    name: string option [@default None];
    (* Namespace is the namespace of the service *)
    namespace: string option [@default None];
    (* If specified, the port on the service that hosting webhook. Default to 443 for backward compatibility. `port` should be a valid port number (1-65535, inclusive). *)
    port: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** ServiceReference holds a reference to Service.legacy.k8s.io *)
let create () : t = {
    name = None;
    namespace = None;
    port = None;
}

