(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_pod_resource_claim.t : PodResourceClaim references exactly one ResourceClaim through a ClaimSource. It adds a name to it that uniquely identifies the ResourceClaim inside the Pod. Containers that need access to the ResourceClaim reference it with this name.
 *)

type t = {
    (* Name uniquely identifies this resource claim inside the pod. This must be a DNS_LABEL. *)
    name: string;
    source: Io_k8s_api_core_v1_claim_source.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** PodResourceClaim references exactly one ResourceClaim through a ClaimSource. It adds a name to it that uniquely identifies the ResourceClaim inside the Pod. Containers that need access to the ResourceClaim reference it with this name. *)
let create (name : string) : t = {
    name = name;
    source = None;
}

