(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_authentication_v1_bound_object_reference.t : BoundObjectReference is a reference to an object that a token is bound to.
 *)

type t = {
    (* API version of the referent. *)
    api_version: string option [@default None] [@key apiVersion];
    (* Kind of the referent. Valid kinds are 'Pod' and 'Secret'. *)
    kind: string option [@default None] [@key kind];
    (* Name of the referent. *)
    name: string option [@default None] [@key name];
    (* UID of the referent. *)
    uid: string option [@default None] [@key uid];
} [@@deriving yojson { strict = false }, show ];;

(** BoundObjectReference is a reference to an object that a token is bound to. *)
let create () : t = {
    api_version = None;
    kind = None;
    name = None;
    uid = None;
}

