(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_node_system_info.t : NodeSystemInfo is a set of ids/uuids to uniquely identify the node.
 *)

[@@@warning "-32-34"]
open (struct
    include Ppx_yojson_conv_lib.Yojson_conv.Primitives
    type any = Yojson.Safe.t
    let any_of_yojson = Fun.id
    let yojson_of_any = Fun.id
    let pp_any = Yojson.Safe.pp
    let show_any = Yojson.Safe.show
end)
type t = {
    (* The Architecture reported by the node *)
    architecture: string [@yojson.key "architecture"];
    (* Boot ID reported by the node. *)
    boot_id: string [@yojson.key "bootID"];
    (* ContainerRuntime Version reported by the node through runtime remote API (e.g. containerd://1.4.2). *)
    container_runtime_version: string [@yojson.key "containerRuntimeVersion"];
    (* Kernel Version reported by the node from 'uname -r' (e.g. 3.16.0-0.bpo.4-amd64). *)
    kernel_version: string [@yojson.key "kernelVersion"];
    (* KubeProxy Version reported by the node. *)
    kube_proxy_version: string [@yojson.key "kubeProxyVersion"];
    (* Kubelet Version reported by the node. *)
    kubelet_version: string [@yojson.key "kubeletVersion"];
    (* MachineID reported by the node. For unique machine identification in the cluster this field is preferred. Learn more from man(5) machine-id: http://man7.org/linux/man-pages/man5/machine-id.5.html *)
    machine_id: string [@yojson.key "machineID"];
    (* The Operating System reported by the node *)
    operating_system: string [@yojson.key "operatingSystem"];
    (* OS Image reported by the node from /etc/os-release (e.g. Debian GNU/Linux 7 (wheezy)). *)
    os_image: string [@yojson.key "osImage"];
    (* SystemUUID reported by the node. For unique machine identification MachineID is preferred. This field is specific to Red Hat hosts https://access.redhat.com/documentation/en-us/red_hat_subscription_management/1/html/rhsm/uuid *)
    system_uuid: string [@yojson.key "systemUUID"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson x =
  try
    Ok (t_of_yojson x)
  with
  | Ppx_yojson_conv_lib.Yojson_conv.Of_yojson_error (e, j) ->
      Error (Printf.sprintf "%s: %s" (Printexc.to_string e) (Yojson.Safe.to_string j))


