(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_apps_v1_daemon_set_update_strategy.t : DaemonSetUpdateStrategy is a struct used to control the update strategy for a DaemonSet.
 *)

type t = {
    rolling_update: Io_k8s_api_apps_v1_rolling_update_daemon_set.t option [@yojson.default None] [@yojson.key "rollingUpdate"];
    (* Type of daemon set update. Can be \''RollingUpdate\'' or \''OnDelete\''. Default is RollingUpdate. *)
    _type: string option [@yojson.default None] [@yojson.key "type"];
} [@@deriving yojson { strict = false }, show, make];;


