(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_autoscaling_v1_horizontal_pod_autoscaler_status.t : current status of a horizontal pod autoscaler
 *)

[@@@warning "-32-34"]
open (struct
    include Ppx_yojson_conv_lib.Yojson_conv.Primitives
    type any = Yojson.Safe.t
    let any_of_yojson = Fun.id
    let yojson_of_any = Fun.id
    let pp_any = Yojson.Safe.pp
    let show_any = Yojson.Safe.show
end)
type t = {
    (* currentCPUUtilizationPercentage is the current average CPU utilization over all pods, represented as a percentage of requested CPU, e.g. 70 means that an average pod is using now 70% of its requested CPU. *)
    current_cpu_utilization_percentage: int32 option [@yojson.default None] [@yojson.key "currentCPUUtilizationPercentage"];
    (* currentReplicas is the current number of replicas of pods managed by this autoscaler. *)
    current_replicas: int32 [@yojson.key "currentReplicas"];
    (* desiredReplicas is the  desired number of replicas of pods managed by this autoscaler. *)
    desired_replicas: int32 [@yojson.key "desiredReplicas"];
    (* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. *)
    last_scale_time: string option [@yojson.default None] [@yojson.key "lastScaleTime"];
    (* observedGeneration is the most recent generation observed by this autoscaler. *)
    observed_generation: int64 option [@yojson.default None] [@yojson.key "observedGeneration"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson x =
  try
    Ok (t_of_yojson x)
  with
  | Ppx_yojson_conv_lib.Yojson_conv.Of_yojson_error (e, j) ->
      Error (Printf.sprintf "%s: %s" (Printexc.to_string e) (Yojson.Safe.to_string j))


