(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_seccomp_profile.t : SeccompProfile defines a pod/container's seccomp profile settings. Only one profile source may be set.
 *)

type t = {
    (* localhostProfile indicates a profile defined in a file on the node should be used. The profile must be preconfigured on the node to work. Must be a descending path, relative to the kubelet's configured seccomp profile location. Must be set if type is \''Localhost\''. Must NOT be set for any other type. *)
    localhost_profile: string option [@default None] [@key localhostProfile];
    (* type indicates which kind of seccomp profile will be applied. Valid options are:  Localhost - a profile defined in a file on the node should be used. RuntimeDefault - the container runtime default profile should be used. Unconfined - no profile should be applied. *)
    _type: string [@key type];
} [@@deriving yojson { strict = false }, show ];;

(** SeccompProfile defines a pod/container's seccomp profile settings. Only one profile source may be set. *)
let create (_type : string) : t = {
    localhost_profile = None;
    _type = _type;
}

