(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_authentication_v1_bound_object_reference.t : BoundObjectReference is a reference to an object that a token is bound to.
 *)

[@@@warning "-32-34"]
open (struct
    include Ppx_yojson_conv_lib.Yojson_conv.Primitives
    type any = Yojson.Safe.t
    let any_of_yojson = Fun.id
    let yojson_of_any = Fun.id
    let pp_any = Yojson.Safe.pp
    let show_any = Yojson.Safe.show
    let string_of_yojson = function
      | `String s -> s
      | `Int i -> string_of_int i
      | _ -> failwith "string_of_yojson: string or int needed"
end)
type t = {
    (* API version of the referent. *)
    api_version: string option [@yojson.default None] [@yojson.key "apiVersion"];
    (* Kind of the referent. Valid kinds are 'Pod' and 'Secret'. *)
    kind: string option [@yojson.default None] [@yojson.key "kind"];
    (* Name of the referent. *)
    name: string option [@yojson.default None] [@yojson.key "name"];
    (* UID of the referent. *)
    uid: string option [@yojson.default None] [@yojson.key "uid"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson x =
  try
    Ok (t_of_yojson x)
  with
  | Ppx_yojson_conv_lib.Yojson_conv.Of_yojson_error (e, j) ->
      Error (Printf.sprintf "%s: %s" (Printexc.to_string e) (Yojson.Safe.to_string j))


