(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_storage_v1_token_request.t : TokenRequest contains parameters of a service account token.
 *)

type t = {
    (* audience is the intended audience of the token in \''TokenRequestSpec\''. It will default to the audiences of kube apiserver. *)
    audience: string [@yojson.key "audience"];
    (* expirationSeconds is the duration of validity of the token in \''TokenRequestSpec\''. It has the same default value of \''ExpirationSeconds\'' in \''TokenRequestSpec\''. *)
    expiration_seconds: int64 option [@yojson.default None] [@yojson.key "expirationSeconds"];
} [@@deriving yojson { strict = false }, show, make];;


