(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_apimachinery_pkg_apis_meta_v1_preconditions.t : Preconditions must be fulfilled before an operation (update, delete, etc.) is carried out.
 *)

open Ppx_yojson_conv_lib.Yojson_conv.Primitives
type t = {
    (* Specifies the target ResourceVersion *)
    resource_version: string option [@yojson.default None] [@yojson.key "resourceVersion"];
    (* Specifies the target UID. *)
    uid: string option [@yojson.default None] [@yojson.key "uid"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson = t_of_yojson


