(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_networking_v1_ingress_spec.t : IngressSpec describes the Ingress the user wishes to exist.
 *)

open Ppx_yojson_conv_lib.Yojson_conv.Primitives
type t = {
    default_backend: Io_k8s_api_networking_v1_ingress_backend.t option [@yojson.default None] [@yojson.key "defaultBackend"];
    (* ingressClassName is the name of an IngressClass cluster resource. Ingress controller implementations use this field to know whether they should be serving this Ingress resource, by a transitive connection (controller -> IngressClass -> Ingress resource). Although the `kubernetes.io/ingress.class` annotation (simple constant name) was never formally defined, it was widely supported by Ingress controllers to create a direct binding between Ingress controller and Ingress resources. Newly created Ingress resources should prefer using the field. However, even though the annotation is officially deprecated, for backwards compatibility reasons, ingress controllers should still honor that annotation if present. *)
    ingress_class_name: string option [@yojson.default None] [@yojson.key "ingressClassName"];
    (* rules is a list of host rules used to configure the Ingress. If unspecified, or no rule matches, all traffic is sent to the default backend. *)
    rules: Io_k8s_api_networking_v1_ingress_rule.t list [@yojson.default []] [@yojson.key "rules"];
    (* tls represents the TLS configuration. Currently the Ingress only supports a single TLS port, 443. If multiple members of this list specify different hosts, they will be multiplexed on the same port according to the hostname specified through the SNI TLS extension, if the ingress controller fulfilling the ingress supports SNI. *)
    tls: Io_k8s_api_networking_v1_ingress_tls.t list [@yojson.default []] [@yojson.key "tls"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson = t_of_yojson


