(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_networking_v1alpha1_ip_address_spec.t : IPAddressSpec describe the attributes in an IP Address.
 *)

type t = {
    parent_ref: Io_k8s_api_networking_v1alpha1_parent_reference.t option [@default None] [@key parentRef];
} [@@deriving yojson { strict = false }, show ];;

(** IPAddressSpec describe the attributes in an IP Address. *)
let create () : t = {
    parent_ref = None;
}

