(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_azure_file_volume_source.t : AzureFile represents an Azure File Service mount on the host and bind mount to the pod.
 *)

type t = {
    (* readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. *)
    read_only: bool option [@yojson.default None] [@yojson.key "readOnly"];
    (* secretName is the  name of secret that contains Azure Storage Account Name and Key *)
    secret_name: string [@yojson.key "secretName"];
    (* shareName is the azure share Name *)
    share_name: string [@yojson.key "shareName"];
} [@@deriving yojson { strict = false }, show, make];;


