(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_networking_v1_ingress_backend.t : IngressBackend describes all endpoints for a given service and port.
 *)

open Ppx_yojson_conv_lib.Yojson_conv.Primitives
type t = {
    resource: Io_k8s_api_core_v1_typed_local_object_reference.t option [@yojson.default None] [@yojson.key "resource"];
    service: Io_k8s_api_networking_v1_ingress_service_backend.t option [@yojson.default None] [@yojson.key "service"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson = t_of_yojson


