(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_autoscaling_v2_object_metric_source.t : ObjectMetricSource indicates how to scale on a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
 *)

type t = {
    described_object: Io_k8s_api_autoscaling_v2_cross_version_object_reference.t [@key "describedObject"];
    metric: Io_k8s_api_autoscaling_v2_metric_identifier.t [@key "metric"];
    target: Io_k8s_api_autoscaling_v2_metric_target.t [@key "target"];
} [@@deriving yojson { strict = false }, show ];;

(** ObjectMetricSource indicates how to scale on a metric describing a kubernetes object (for example, hits-per-second on an Ingress object). *)
let create (described_object : Io_k8s_api_autoscaling_v2_cross_version_object_reference.t) (metric : Io_k8s_api_autoscaling_v2_metric_identifier.t) (target : Io_k8s_api_autoscaling_v2_metric_target.t) : t = {
    described_object = described_object;
    metric = metric;
    target = target;
}

