(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_apiserverinternal_v1alpha1_storage_version_condition.t : Describes the state of the storageVersion at a certain point.
 *)

type t = {
    (* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. *)
    last_transition_time: string option [@default None] [@key lastTransitionTime];
    (* A human readable message indicating details about the transition. *)
    message: string option [@default None] [@key message];
    (* If set, this represents the .metadata.generation that the condition was set based upon. *)
    observed_generation: int64 option [@default None] [@key observedGeneration];
    (* The reason for the condition's last transition. *)
    reason: string [@key reason];
    (* Status of the condition, one of True, False, Unknown. *)
    status: string [@key status];
    (* Type of the condition. *)
    _type: string [@key type];
} [@@deriving yojson { strict = false }, show ];;

(** Describes the state of the storageVersion at a certain point. *)
let create (reason : string) (status : string) (_type : string) : t = {
    last_transition_time = None;
    message = None;
    observed_generation = None;
    reason = reason;
    status = status;
    _type = _type;
}

