(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_autoscaling_v2_external_metric_status.t : ExternalMetricStatus indicates the current value of a global metric not associated with any Kubernetes object.
 *)

open Ppx_yojson_conv_lib.Yojson_conv.Primitives
type t = {
    current: Io_k8s_api_autoscaling_v2_metric_value_status.t [@yojson.key "current"];
    metric: Io_k8s_api_autoscaling_v2_metric_identifier.t [@yojson.key "metric"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson = t_of_yojson


