(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_volume_node_affinity.t : VolumeNodeAffinity defines constraints that limit what nodes this volume can be accessed from.
 *)

type t = {
    required: Io_k8s_api_core_v1_node_selector.t option [@yojson.default None] [@yojson.key "required"];
} [@@deriving yojson { strict = false }, show, make];;


