(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_sysctl.t : Sysctl defines a kernel parameter to be set
 *)

open Ppx_yojson_conv_lib.Yojson_conv.Primitives
type t = {
    (* Name of a property to set *)
    name: string [@yojson.key "name"];
    (* Value of a property to set *)
    value: string [@yojson.key "value"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson = t_of_yojson


