(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_core_v1_local_object_reference.t : LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.
 *)

type t = {
    (* Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names *)
    name: string option [@default None] [@key "name"];
} [@@deriving yojson { strict = false }, show ];;

(** LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace. *)
let create () : t = {
    name = None;
}

