(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Port number of the gRPC service. Number must be in the range 1 to 65535. *)
    port: int32 [@yojson.key "port"];
    (* Service is the name of the service to place in the gRPC HealthCheckRequest (see https://github.com/grpc/grpc/blob/master/doc/health-checking.md).  If this is not specified, the default behavior is defined by gRPC. *)
    service: string option [@yojson.default None] [@yojson.key "service"];
} [@@deriving yojson { strict = false }, show, make];;


