(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Io_k8s_api_resource_v1alpha2_resource_claim_spec.t : ResourceClaimSpec defines how a resource is to be allocated.
 *)

[@@@warning "-32-34"]
open (struct
    include Ppx_yojson_conv_lib.Yojson_conv.Primitives
    type any = Yojson.Safe.t
    let any_of_yojson = Fun.id
    let yojson_of_any = Fun.id
    let pp_any = Yojson.Safe.pp
    let show_any = Yojson.Safe.show
    let string_of_yojson = function
      | `String s -> s
      | `Int i -> string_of_int i
      | _ -> failwith "string_of_yojson: string or int needed"
end)
type t = {
    (* Allocation can start immediately or when a Pod wants to use the resource. \''WaitForFirstConsumer\'' is the default. *)
    allocation_mode: string option [@yojson.default None] [@yojson.key "allocationMode"];
    parameters_ref: Io_k8s_api_resource_v1alpha2_resource_claim_parameters_reference.t option [@yojson.default None] [@yojson.key "parametersRef"];
    (* ResourceClassName references the driver and additional parameters via the name of a ResourceClass that was created as part of the driver deployment. *)
    resource_class_name: string [@yojson.key "resourceClassName"];
} [@@deriving yojson, show, make] [@@yojson.allow_extra_fields];;
let to_yojson = yojson_of_t
let of_yojson x =
  try
    Ok (t_of_yojson x)
  with
  | Ppx_yojson_conv_lib.Yojson_conv.Of_yojson_error (e, j) ->
      Error (Printf.sprintf "%s: %s" (Printexc.to_string e) (Yojson.Safe.to_string j))


